
version: '3.8'

services:
  # Your Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    depends_on:
      db:
        condition: service_healthy
      kong:
        condition: service_started

# Include all the Supabase services from its own docker-compose file
include:
  - ./supabase/docker-compose.yml 